package com.plug.world.entity.player.content.skills;

public enum SkillType {

	ATTACK, DEFENCE, STRENGTH, HITPOINTS, RANGE, PRAYER, MAGIC, FISHING, COOKING, FLETCHING, CRAFTING, SMITHING, MINING, HERBLORE, SLAYER, RUNECRAFTING, FARMING, WOODCUTTING, FIREMAKING, AGILITY, THIEVING, HUNTER

}
